// templates/VtPagination.vue
<template>
        <pagination
                :options="props.optionsObj"
                :for="props.name"
                :vuex="props.vuex"
                :records="props.records"
                :per-page="props.perPage"
                v-model="props.page"
                @paginate="paginate"/>
</template>

<script>
    import Pagination from 'vue-pagi-vwi'

    export default {
        name: "MyPagination",
        components: {
            Pagination
        },
        props: ['props'],
        methods: {
            paginate(page) {
                this.$emit('paginate', this.props.page);
                return this.props.setPage(page)
            }
        }
    }
</script>

// lib/components/VtPagination.jsx
import RLPagination from "./renderless/RLPagination";
import Pagination from "vue-pagi-vwi";

export default {
    name: 'VtPagination',
    components: {RLPagination, Pagination},
    render(h) {
        return <r-l-pagination scopedSlots={
            {
                default: function (props) {
                    return props.override ? h(
                        props.override,
                        {
                            attrs: {props}
                        }
                    ) : <pagination
                        options={props.optionsObj}
                        for={props.name}
                        vuex={props.vuex}
                        records={props.records}
                        per-page={props.perPage}
                        page={props.page}
                        onPaginate={page => props.setPage(page)}>
                    </pagination>
                }
            }
        }
            >

            </r-l-pagination>
        }
}
